export enum HTTP_STATUS {
  OK = 200,
  INTERNAL_SERVER_ERROR = 500,
  NOTFOUND = 404,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
}

export const HTTP_RESPONSE_MESSAGES: Record<number, string> = {
  [HTTP_STATUS.OK]: '成功!',
  [HTTP_STATUS.INTERNAL_SERVER_ERROR]: '失败',
  [HTTP_STATUS.NOTFOUND]: '404',
  [HTTP_STATUS.UNAUTHORIZED]: '无权限',
}
